version: "3.4"
services:
  travix.userservice:
    image: ${DOCKER_REGISTRY-}usermicroservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
      dockerfile: Microservices/UserService/API/Dockerfile
    ports:
      - "5010:5010"
  travix.bookingservice:
    image: ${DOCKER_REGISTRY-}bookingmicroservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
      dockerfile: Microservices/BookingService/API/Dockerfile
    ports:
      - "5009:5009"

  travix.api:
    image: ${DOCKER_REGISTRY-}travixapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
      dockerfile: API/TravixBackend.API/Dockerfile
    ports:
      - "3003:3003"
    links:
      - "travix.bookingservice"
      - "travix.userservice"
