// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TravixBackend.BookingService.Domain;

#nullable disable

namespace TravixBackend.BookingService.Domain.Migrations
{
    [DbContext(typeof(TravixBackendDBContext))]
    partial class TravixBackendDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TravixBackend.BookingService.Domain.Data.Entities.Booking", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ArrivalTime")
                        .HasColumnType("text")
                        .HasColumnName("arrivalTime");

                    b.Property<string>("Cost")
                        .HasColumnType("text")
                        .HasColumnName("cost");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Date")
                        .HasColumnType("text")
                        .HasColumnName("date");

                    b.Property<string>("Departing")
                        .HasColumnType("text")
                        .HasColumnName("departingAt");

                    b.Property<string>("FlightCode")
                        .HasColumnType("text")
                        .HasColumnName("flightCode");

                    b.Property<string>("From")
                        .HasColumnType("text")
                        .HasColumnName("from");

                    b.Property<string>("Group")
                        .HasColumnType("text")
                        .HasColumnName("group");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PassportNo")
                        .HasColumnType("text")
                        .HasColumnName("passportNo");

                    b.Property<string>("Seat")
                        .HasColumnType("text")
                        .HasColumnName("seat");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("To")
                        .HasColumnType("text")
                        .HasColumnName("to");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<string>("Way")
                        .HasColumnType("text")
                        .HasColumnName("way");

                    b.HasKey("Id");

                    b.ToTable("bookings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
